categories:
  reserve:
    label: 'reserve'
  reserve.templates:
    label: 'Templates'
    parent: reserve
  reserve.pages:
    label: 'Pages'
    parent: reserve
  reserve.settings:
    label: 'Settings'
    parent: reserve

settings:
  reserve.templateRootPath:
    label: 'Templates'
    category: reserve.templates
    description: 'Path to template root'
    type: string
    default: 'EXT:reserve/Resources/Private/Templates/'
  reserve.partialRootPath:
    label: 'Partials'
    category: reserve.templates
    description: 'Path to partial root'
    type: string
    default: 'EXT:reserve/Resources/Private/Partials/'
  reserve.layoutRootPath:
    label: 'Layouts'
    category: reserve.templates
    description: 'Path to layout root'
    type: string
    default: 'EXT:reserve/Resources/Private/Layouts/'
  reserve.storagePid:
    label: 'Default storage PID'
    category: reserve.settings
    description: 'Folder that stores all POIs'
    type: int
    default: 0
  reserve.requiredFormFields:
    label: 'Comma separated list of required form fields'
    category: reserve.settings
    description: ''
    type: string
    default: 'lastName,firstName,email,phone,address,zip,city'
