services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  JWeiland\Reserve\:
    resource: '../Classes/*'

  JWeiland\Reserve\Tca\CreateForeignTableColumns:
    tags:
      - name: event.listener
        identifier: 'reserve-createforeigntablecolumns'
        method: 'addEvents2DatabaseColumnsToTablesDefinition'
        event: TYPO3\CMS\Core\Database\Event\AlterTableDefinitionStatementsEvent
